const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Sprite: 0},
	{TiledBackground: 0},
	{Solid: 0},
	{Jumpthru: 0},
	{TiledBackground2: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sine: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Text: 0},
	{start: 0},
	{Mouse: 0},
	{Text2: 0},
	{menu: 0},
	{Text3: 0},
	{Sprite6: 0},
	{TiledBackground5: 0},
	{TiledBackground6: 0},
	{Text4: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	start: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Text2: class extends self.ITextInstance {},
	menu: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	Text4: class extends self.ITextInstance {}
}